### ISSUE TITLE
v.io/x/ref/services/agent/internal/launcher: TestStaleLockMany test fails.

### ISSUE THREAD

**Issue by joeblew99** [vanadium/core#2]
as this test was running it tried to open a network connection, which i allowed

````
?   	v.io/x/ref/services/agent/internal/launcher	[no test files]
--- FAIL: TestStaleLockMany (0.07s)
	lock_test.go:714: Error (0): pipe: too many open files
FAIL
FAIL	v.io/x/ref/services/agent/internal/lock	5.724s

````

**Comment by razvanm** [comment]
The `lock` directory doesn't exist in the vanadium/core repo: [go/src/v.io/x/ref/services/internal](https://github.com/vanadium/core/tree/f3fdd729c0c2c20162ad0b223f1a2517e5350c46/go/src/v.io/x/ref/services/internal)

**Comment by joeblew99** [comment]
Thanks for the answers.

1. I would prefer if this can be run with the federation style server running locally. In my case I would want to run the federation server on the local lan.

2. syncbase. Is this included in core ?

3. Do you support rpc with a web client ?

**Comment by razvanm** [comment]
Sorry for the late reply.

1. What exactly is _this_? Vanadium Core? A particular test? Something else? :-)

2. Nope, Syncbase is not part of the Vanadium Core repo. It adds a lot of code and inconvenient non-Go dependencies (leveldb and snappy).

3. For now the answer is no. The [vanadium-console](https://github.com/razvanm/vanadium-console) (still work-in-progress) is issuing Vanadium RPCs from a Chrome App using a modified Go 1.3 toolchain. Getting things to work on Go 1.7 would take some effort.

**Comment by razvanm** [comment]
I'm marking this as closed because the discussion is not about the initial issue anymore.
